import * as vscode from 'vscode';
import { strict as assert } from 'node:assert';
import * as path from 'node:path';
import { chromium } from 'playwright-core';
import type { Runtime } from '../extension';
import { TOOL_NAME } from '../core';

export async function run(): Promise<void> {
    const extension = vscode.extensions.getExtension<Runtime>('davidle-ms.agent-context-trace');
    assert.ok(extension, 'Development extension is installed');
    const runtime = await extension.activate();
    assert.ok(runtime, 'Extension activated in a trusted local test workspace');
    assert.ok(vscode.lm.tools.some(tool => tool.name === TOOL_NAME), 'Tool registered with the host');
    const roots = await runtime.view.getChildren();
    assert.equal(roots.length, 2);
    const children = await runtime.view.getChildren(roots[0]);
    const source = children.find(node => node.name === 'source.ts')!;
    const neutral = children.find(node => node.name === 'neutral.ts')!;
    const other = (await runtime.view.getChildren(roots[1])).find(node => node.name === 'source.ts')!;
    assert.ok(source && neutral && other);
    runtime.view.getTreeItem(source);
    runtime.view.getTreeItem(neutral);
    runtime.view.getTreeItem(other);
    const sourceUri = runtime.view.uri(source);
    if (process.env.ACT_TEST_PHASE === 'restore') {
        const previous = runtime.store.list().find(session => session.label === 'Host test');
        assert.ok(previous, 'Session JSON restored independently of test-mode workspace state');
        await runtime.view.selectSession(previous.id);
        assert.equal(runtime.view.enabled, true, 'VS Code extension-test mode intentionally resets workspace state');
        assert.equal(runtime.view.selected()?.events.length, 3, 'Session metadata restored');
        assert.equal(runtime.store.current(), undefined, 'Historical session not automatically recording');
        assert.equal(runtime.view.provideFileDecoration(sourceUri)?.badge, 'R');
        const selected = runtime.view.selected()!;
        await runtime.store.delete(selected.id);
        assert.equal(runtime.view.provideFileDecoration(sourceUri), undefined, 'Deletion removes markers');
        console.log('PASS: session JSON restore, no auto-recording, deletion; workspace preference tested in normal development hosts');
        return;
    }
    const sessionId = await runtime.start('Host test');
    const root = runtime.roots.find(candidate => candidate.id === source.rootId)!;
    const filePath = path.join(root.directory, source.relativePath);
    const token = new vscode.CancellationTokenSource();
    const invoke = (overrides = {}) => runtime.read({ input: { sessionId, filePath, startLine: 2, endLine: 3, ...overrides }, toolInvocationToken: undefined }, token.token);
    assert.equal(runtime.view.enabled, true);
    assert.equal(runtime.store.get(sessionId)?.events.length, 0, 'Tree enumeration does not create reads');
    const result = await invoke();
    assert.ok((result.content[0] as vscode.LanguageModelTextPart).value.endsWith('2: second\n3: third'));
    assert.equal(runtime.view.provideFileDecoration(sourceUri)?.badge, 'R');
    assert.equal(runtime.view.provideFileDecoration(runtime.view.uri(neutral)), undefined);
    assert.equal(runtime.view.provideFileDecoration(runtime.view.uri(other)), undefined, 'Multi-root identity is isolated');
    assert.equal(runtime.view.provideFileDecoration(vscode.Uri.file(filePath)), undefined, 'Real Explorer/tab URIs are untouched');
    assert.equal(runtime.view.provideFileDecoration(runtime.view.uri(roots[0]!)), undefined, 'Folders are neutral');
    await assert.rejects(invoke({ filePath: path.join(root.directory, '.env') }));
    const configuration = vscode.workspace.getConfiguration('agentContextTrace');
    await configuration.update('excludeGlobs', ['**/source.ts'], vscode.ConfigurationTarget.Global);
    await assert.rejects(invoke(), /excluded/);
    await configuration.update('excludeGlobs', [], vscode.ConfigurationTarget.Global);
    await runtime.view.toggle();
    assert.equal(runtime.view.provideFileDecoration(sourceUri), undefined);
    await invoke({ startLine: 1, endLine: 1 });
    assert.equal(runtime.store.get(sessionId)?.events.length, 2, 'Recording continues with colors off');
    await runtime.view.toggle();
    assert.equal(runtime.view.provideFileDecoration(sourceUri)?.badge, 'R');
    const document = await vscode.workspace.openTextDocument(filePath);
    const edit = new vscode.WorkspaceEdit();
    edit.insert(document.uri, new vscode.Position(0, 0), 'dirty ');
    assert.equal(await vscode.workspace.applyEdit(edit), true);
    await invoke({ startLine: 1, endLine: 1 });
    assert.equal(runtime.store.get(sessionId)?.events.at(-1)?.isDirty, true);
    await document.save();
    token.cancel();
    await assert.rejects(invoke());
    token.dispose();
    assert.equal(runtime.store.get(sessionId)?.events.length, 3, 'Denied and cancelled calls do not create read markers');
    await runtime.store.setState(sessionId, 'paused');
    const fresh = new vscode.CancellationTokenSource();
    await assert.rejects(runtime.read({ input: { sessionId, filePath, startLine: 1, endLine: 1 }, toolInvocationToken: undefined }, fresh.token));
    fresh.dispose();
    await runtime.store.setState(sessionId, 'stopped');
    const second = await runtime.start('Empty history');
    assert.equal(runtime.view.provideFileDecoration(sourceUri), undefined, 'New selected session clears old colors');
    await runtime.store.setState(second, 'stopped');
    await runtime.view.selectSession(sessionId);
    assert.equal(runtime.view.provideFileDecoration(sourceUri)?.badge, 'R');
    await vscode.commands.executeCommand('agentContextTrace.readCoverage.focus');
    await runtime.view.tree.reveal(source, { select: false, focus: false, expand: true });
    const browser = await chromium.connectOverCDP(`http://127.0.0.1:${process.env.ACT_CDP_PORT}`);
    try {
        const page = browser.contexts().flatMap(context => context.pages()).find(candidate => candidate.url().includes('workbench'));
        assert.ok(page, 'Native VS Code workbench renderer is reachable');
        const section = page.locator('.pane').filter({ has: page.getByText('Agent Read Coverage', { exact: true }) }).first();
        await section.waitFor({ state: 'visible' });
        const label = section.locator('.monaco-icon-label').filter({ hasText: 'source.ts' }).first();
        await label.waitFor({ state: 'visible' });
        await page.waitForFunction(() => {
            const pane = Array.from(globalThis.document.querySelectorAll('.pane')).find(element => element.textContent?.includes('Agent Read Coverage'));
            const target = Array.from(pane?.querySelectorAll('.label-name') ?? []).find(element => element.textContent === 'source.ts');
            return target && getComputedStyle(target).color === 'rgb(112, 187, 255)';
        });
        const colored = await label.evaluate(element => getComputedStyle(element.querySelector('.label-name') ?? element).color);
        await page.screenshot({ path: path.join(process.env.ACT_SCREENSHOTS!, 'read-colors-on.png') });
        await runtime.view.toggle();
        await page.waitForFunction(previous => {
            const panes = Array.from(globalThis.document.querySelectorAll('.pane'));
            const pane = panes.find(element => element.textContent?.includes('Agent Read Coverage'));
            const target = Array.from(pane?.querySelectorAll('.label-name') ?? []).find(element => element.textContent === 'source.ts');
            return target && getComputedStyle(target).color !== previous;
        }, colored);
        await page.screenshot({ path: path.join(process.env.ACT_SCREENSHOTS!, 'read-colors-off.png') });
        assert.equal(runtime.view.enabled, false);
    } finally { await browser.close(); }
    console.log('PASS: registered tool, numbered read, file colors, native rendering toggle, neutral files, scope, exclusions, dirty buffers, cancellation, session selection');
    await vscode.commands.executeCommand('workbench.action.quit');
}